name: cats-time
baseurl: /cats-time
description: Cats Typeclasses for Java Time
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.4+10-8e3b6e86-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
