name: cats-time
baseurl: /cats-time
description: Cats Typeclasses for Java Time
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.1-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
